### PR TITLE
Unit serde replicates VoidSerde, use case for when no key or value.

### PR DESCRIPTION
**Pull request by JohnSColeman**
A unit Serde performs a similar function to the Kafka VoidSerde to provide a type for values that should be null, typically to explicitly indicate the use case where messages do not utilise a key value.

Serialization and deserialization will always produce a null. This behaviour is unlike VoidSerde which will throw an exception when a non-null value is presented for deserialization.

### CODE REVIEW

**Comment by natansil** [comment]
@JohnSColeman can you please push a dummy commit to this branch to trigger the test?
(There was a technical issue that prevented running the test)

On our private repo the test ran, and there was an error:
`data-streams/greyhound/core/src/main/scala/com/wixpress/dst/greyhound/core/Serde.scala:4: error: value VoidSerde is not a member of object org.apache.kafka.common.serialization.Serdes`

It seems like VoidSerde was added from kafka client version **2.5**
We currently depend on kakfa/kafka-clients **2.4.1**

We will try to upgrade kafka version soon.
I will update here when we do it.
Sorry about this.

**Comment by JohnSColeman** [comment]
> @JohnSColeman can you please push a dummy commit to this branch to trigger the test?
> (There was a technical issue that prevented running the test)
> 
> On our private repo the test ran, and there was an error:
> `data-streams/greyhound/core/src/main/scala/com/wixpress/dst/greyhound/core/Serde.scala:4: error: value VoidSerde is not a member of object org.apache.kafka.common.serialization.Serdes`
> 
> It seems like VoidSerde was added from kafka client version **2.5**
> We currently depend on kakfa/kafka-clients **2.4.1**
> 
> We will try to upgrade kafka version soon.
> I will update here when we do it.
> Sorry about this.

I have updated the kafka client to the more recent 2.7.0 version which builds ok - Is there an integration test to verify this change?

Where would you suggest I create a unit test for the new UnitSerde?

**Comment by natansil** [comment]
Hi John,

Unfortunately, this PR build is still not passing on Wix private repo.
We are working hard at Wix private repo to upgrade to kafka 2.7.0
It required us to need to upgrade the Scala version, which caused more issues to crop up.

I will keep you updated about our progress,
Sorry for the long wait here.

**Comment by natansil** [comment]
we're getting close to switching Scala version :)

> Where would you suggest I create a unit test for the new UnitSerde?

You can add one [here](https://github.com/wix/greyhound/tree/master/core/src/test/scala/com/wixpress/dst/greyhound/core/serialization)
Should be written in specs2, you can see examples there.

**Comment by natansil** [comment]
@JohnColeman-CTO I'm sorry we haven't merged this yet.

We've managed to upgrade scala version.
We still need to work out issues with the upgraded zookeeper version in our interval ecosystem tests.

I will let you know asap that is resolved.

Sorry again

**Comment by JohnSColeman** [comment]
Hi,

I have taken a fresh fork and included tests for the UnitSerde.

John

**Comment by natansil** [comment]
Cool. Thanks

**Pull request closed without merging**
