### PR TITLE
upgrade to ZIO 1.0.1

### PR DESCRIPTION
**Pull request by dkarlinsky**
#pr

### CODE REVIEW

**Comment by dkarlinsky** [comment]
#automerge

**Comment by dkarlinsky** [comment]
#automerge

**Comment by cbcoutinho** [comment]
@dkarlinsky Can you please bump and deploy a new patch version of this library so that the latest ZIO version is included?

I can submit a PR if you like

**Comment by dkarlinsky** [comment]
@cbcoutinho done (#226)

**Comment by natansil** [comment]
Hi @cbcoutinho,
Are you using Greyhound?

**Comment by cbcoutinho** [comment]
Hi @natansil yes, we're looking into Greyhound for a small side project of ours.

Thanks for the quick reply @dkarlinsky - there seems to have been an API change between ZIO 1.0.0-RC23 and 1.0.3, which got in the way when we were looking into this last week. I appreciate the update!

I'm assuming this will also bump greyhound to 0.1.3?

**Comment by natansil** [comment]
Sounds good.
We would love to get any feedback you have, including missing features, bugs, or unexpected behaviour.
Feel free to open any issue you feel like :)

**Comment by natansil** [comment]
> I'm assuming this will also bump greyhound to 0.1.3?
@dkarlinsky are we stable in terms of CI?
If so, then I will cut a version ASAP

**Comment by dkarlinsky** [comment]
@natansil seems stable now, after I added `--flaky_test_attempts=3` :)

**Comment by natansil** [comment]
@cbcoutinho version 0.1.3 is released.
It takes a little time for the jars to be mirrored to https://repo1.maven.org/maven2/
So you can also add this repository: https://oss.sonatype.org/content/groups/public

**Pull request merged**
